### ISSUE TITLE
[Manifest] Add() not allowing my local filepath

### ISSUE THREAD

**Issue by dandanxu** [solvebio/solvebio-python#101]
```
manifest = solvebio.Manifest()
manifest.add(path='~/Desktop/data.json.gz')
```
is causing

`ValueError: Paths in manifest must be valid URL (starting with http:// or https://) or a valid local filename, directory, or glob (such as: *.vcf)`

Maybe something in /resource/manifest.py is not recognizing tildes?

**Comment by jsh2134** [comment]
i had this same issue, need to use full path
