### ISSUE TITLE
Display upload percentage for file uploads

### ISSUE THREAD

**Issue by dandanxu** [solvebio/solvebio-python#119]
For uploading large files (1Gb and etc), hard to tell if the upload is stalled/glitched or if it's still running.

**Comment by davecap** [comment]
Actually kind of tricky (impossible?) with direct to S3 uploads using python-requests, unless we can figure out how to do multi-part form-based uploads. In the short term we might have to show a spinner in the console (without actual progress %).

**Comment by davecap** [comment]
Turns out you should never say never because this was actually simpler than I thought :)
