### ISSUE TITLE
Can not import without a template in (update-genome branch)

### ISSUE THREAD

**Issue by igersh** [solvebio/solvebio-python#127]
when importing with this branch it breaks if you don't have a template and it should allow it.

`Cannot create a new dataset: must specify a template ID with the --template-id flag, or provide a template file with --template-file`

**Comment by davecap** [comment]
Is it possible to run the command without specifying `--create-dataset` ?

**Comment by jsh2134** [comment]
#126

**Comment by davecap** [comment]
Is this closed?
