### ISSUE TITLE
Update DatasetImport follow() function to follow DatasetCommits as well

### ISSUE THREAD

**Issue by jsh2134** [solvebio/solvebio-python#133]
Imports and Commits were decoupled in December-ish. 

https://github.com/solvebio/solvebio-python/blob/52b83331d7448179cc3f5df7277499eee546776f/solvebio/resource/datasetimport.py#L32

Once the import gets to the  `complete` state check for commits and follow() those

**Comment by davecap** [comment]
What if there are lots of commits?

**Comment by davecap** [comment]
Add this to Dataset Migrations as well.

**Comment by jsh2134** [comment]
if there are multiple commits, should it loop through each commit and print the status of each...or just start with the first?

**Comment by davecap** [comment]
Probably show them all?
