### ISSUE TITLE
More robust follow() function

### ISSUE THREAD

**Issue by jsh2134** [solvebio/solvebio-python#134]
when follow() - ing a long running task like imports/exports, sometimes the refresh() fails with a lost connection. 

this can be frustrating for scripts that are trying to run many things over a long period of time. one option is to just have the script writer handle this case, another is to make the follow() function more robust and retry on failure connections

**Comment by davecap** [comment]
@jsh2134 see the PR about the connection retries in the client. This should address this issue.
