### ISSUE TITLE
Allow `solvebio import` to take a dataset capacity argument

### ISSUE THREAD

**Issue by jsh2134** [solvebio/solvebio-python#135]
allow this argument to be passed when creating a new dataset in the import command with the --create-dataset shortcut

a user can already do this with the client by creating a dataset first, just not with the all-in-one command. not sure if we should add this option as well. an alternate approach is to include the capacity in the dataset_template used

**Comment by jsh2134** [comment]
(customer request)

**Comment by dandanxu** [comment]
^ it'd be good to know what the possible options are too - is it `small`, `medium`, `large`?

**Comment by davecap** [comment]
Actually we have `tall`, `grande`, and `venti`.
