### ISSUE TITLE
Add "upload" command-line sub-command

### ISSUE THREAD

**Issue by davecap** [solvebio/solvebio-python#149]
It would be nice to have an `upload` sub-command similar to `import` but that just uploads one or more files into a vault folder.

**Comment by davecap** [comment]
Should we make the "vault path" as the first positional arg? or should it be a flag?

```
solvebio upload <dest> <file globs>
```

or 

```
solvebio upload --path /vault/path <file globs>
```

**Comment by jhuttner** [comment]
I think positional argument.  Every upload has a "Parent Logical Object", which for "/" is just None.  
So it makes sense to me that it would be positional, since it is required..

**Comment by davecap** [comment]
I guess the user will have to also provide the vault ID, but it can technically be be the first part of the path right?

**Comment by jhuttner** [comment]
Yes.

**Comment by davecap** [comment]
What about if no dest. is provided, the uploads go into the user's private vault ("Uploads" folder)?

**Comment by jhuttner** [comment]
Maybe the syntax should mimic the "cp" or "scp" command?

"cp file /path/to/dest" (indicates user's private vault)

"cp file vault_name:/path/to/dest"

Additionally, I think the user should be able to specify the vault by name.  I think having to specify by ID is onerous.

**Comment by davecap** [comment]
Yea I think that makes sense as well.

**Comment by davecap** [comment]
Will remove from v1.16.0 and add it to a future release milestone.

**Comment by jsh2134** [comment]
implemented in https://github.com/solvebio/solvebio-python/pull/172/files#diff-04c6e90faac2675aa89e2176d2eec7d8R341
