### ISSUE TITLE
Dataset export of a query requires a limit

### ISSUE THREAD

**Issue by dandanxu** [solvebio/solvebio-python#167]
I'm trying to download all of HGNC but with just 2 fields and following the instructions in the new developer docs.

```
In [9]: dataset = Dataset.retrieve('HGNC/3.0.0-2017-03-01/HGNC')

In [10]: query = dataset.query(fields=['gene_symbol', 'name'])

In [11]: export = query.export(format='csv',follow=True)
```

results in
`SolveError: Bad request. {u'limit': [u"'limit' must be between 1 and 1000000"]}`

It seems that like if I can download the entire dataset with just Dataset.retrieve().export, I should be able to do the same with a subset of the fields? 
The download works if I set
`query = dataset.query(fields=['gene_symbol', 'name'], limit=100000)`

**Comment by jsh2134** [comment]
closed with #169
