### ISSUE TITLE
File upload with version 2.1.0 on Windows 7

### ISSUE THREAD

**Issue by sajohn2** [solvebio/solvebio-python#189]
When trying to upload a file using the following command on Windows 7:

`uploaded_file = vault.upload_file('data.json.gz', '/')`

 I'm getting:
`FileNotFoundError: [WinError 3] The system cannot find the path specified: '/dev/null'`

The culprit may or may not be the following line solvebio\resource\object.py:
`if md5sum('/dev/null')[0] == md5:`

**Comment by davecap** [comment]
Thanks for the bug report. I just pushed a potential fix for this. If possible, would you be able to test it out?

To install the branch from your shell (requires pip):

```
pip install git+https://github.com/solvebio/solvebio-python.git@fix-devnull
```

**Comment by sajohn2** [comment]
Well, slightly different problem now, there is the tb:

OSError                                   Traceback (most recent call last)

     20 # dataset.import_file('data.json.gz')     21 ---> 22
uploaded_file = vault.upload_file('data-test.json', '/')     23
24 imp = DatasetImport.create(dataset_id=dataset.id,
object_id=uploaded_file.id)
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\solvebio\resource\vault.py
in upload_file(self, local_path, remote_path)     92     def
upload_file(self, local_path, remote_path):     93         from
solvebio import Object---> 94         return
Object.upload_file(local_path, remote_path, self.name)     95      96
   def search(self, query, **params):
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\solvebio\resource\object.py
in upload_file(cls, local_path, remote_path, vault_name)     68
 size = os.path.getsize(local_path)     69 ---> 70         if
md5sum(os.devnull)[0] == md5:     71             print(('Notice:
Cannot upload empty file {0}'.format(local_path)))     72
return
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\solvebio\utils\md5sum.py
in md5sum(path, multipart_threshold, multipart_chunksize)     17
      chunk = f.read(chunk_size)     18 ---> 19     filesize =
os.path.getsize(path)     20      21     with open(path, "rb") as f:
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\genericpath.py
in getsize(filename)     48 def getsize(filename):     49
"""Return the size of a file, reported by os.stat()."""---> 50
return os.stat(filename).st_size     51      52
OSError: [WinError 1] Incorrect function: 'nul'

**Comment by davecap** [comment]
It seems that "/dev/null" isn't always enabled in Windows, which is likely what happened here. I've just pushed a change to the same branch that should hopefully work! Can you try re-installing from the branch and try that out?

**Comment by sajohn2** [comment]
It looks like we are almost there. For a plain text JSONL format it looks
like the upload starts but then comes back with a 400 Bad Request. I
couldn't tell if I was doing something that caused this, but the JSONL file
uploads without issue through the web GUI and used it to create a data set.

import solvebio
from solvebio import Vault

import requests
import logging

import http.client as http_client
http_client.HTTPConnection.debuglevel = 1

solvebio.login(api_key='MY_SECRET_KEY')

vault = Vault.get_personal_vault()

with open('data-test.json', 'w') as ofs:
    ofs.write(processed_table_df.to_json(orient='records', lines=True))

uploaded_file = vault.upload_file('data-test.json', '/')


This produces the following HTTP logs (I redacted some of the header vars
with XXXXXXXXXX and replaced by size-able JSONL file with "REALLY BIG FILE
HERE"):


end: b'CONNECT solvebio-secure-production.s3.amazonaws.com:443 HTTP/1.0\r\n'
send: b'\r\n'
send: b'PUT /uploads/1611/547828171720003453?AWSAccessKeyId=XXXXXXXXXX&x-amz-acl=private&Expires=1505849207&content-md5=t2M64hZbjs%2BvYJk8P6kKwg%3D%3D&Signature=XXXXXXXXXX&x-amz-server-side-encryption=AES256
HTTP/1.1\r\nHost:
solvebio-secure-production.s3.amazonaws.com\r\nUser-Agent:
python-requests/2.18.4\r\nAccept-Encoding: gzip, deflate\r\nAccept:
*/*\r\nConnection: keep-alive\r\nContent-MD5:
t2M64hZbjs+vYJk8P6kKwg==\r\nContent-Length: 15207\r\n\r\n'

sendIng a read()able
encoding file using iso-8859-1

send: b'{"REALLY BIG FILE HERE"}

reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Date header: Connection header: Transfer-Encoding header:
x-amz-id-2 header: x-amz-request-id header: Content-Type Notice:
Upload status code for data-test.json was 400
send: b'DELETE /v2/objects/547828171642757250 HTTP/1.1\r\nHost:
api.solvebio.com\r\nUser-Agent: SolveBio Python Client 2.1.0 [Python
CPython/3.6.1]\r\nAccept-Encoding: gzip,deflate\r\nAccept:
application/json\r\nConnection: keep-alive\r\nContent-Type:
application/json\r\nContent-Length: 2\r\nAuthorization: Token
XXXXXXXXXX\r\n\r\n'
send: b'{}'

reply: 'HTTP/1.1 200 OK\r\n'
header: Allow header: Content-Encoding header: Content-Type header:
Date header: Server header: SolveBio-Version header:
Strict-Transport-Security header: Vary header: X-Frame-Options header:
Content-Length header: Connection


There is a separate issue with a Python gzipped file:

import gzip
import solvebio
from solvebio import Vault

import requests
import logging

import http.client as http_client
http_client.HTTPConnection.debuglevel = 1

solvebio.login(api_key='MY_SECRET_KEY')

vault = Vault.get_personal_vault()

with gzip.open('data-test.json.gz', 'wb') as ofs:
    ofs.write(processed_table_df.to_json(orient='records',
lines=True).encode())

uploaded_file = vault.upload_file('data-test.json.gz', '/')

Ends up yielding:

---------------------------------------------------------------------------UnicodeDecodeError
                       Traceback (most recent call
last)<ipython-input-8-fd8971f60ab8> in <module>()     31 #
dataset.import_file('data.json.gz')     32 ---> 33 uploaded_file =
vault.upload_file('data-test.json.gz', '/')     34      35 #imp =
DatasetImport.create(dataset_id=dataset.id,
object_id=uploaded_file.id)
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\solvebio\resource\vault.py
in upload_file(self, local_path, remote_path)     92     def
upload_file(self, local_path, remote_path):     93         from
solvebio import Object---> 94         return
Object.upload_file(local_path, remote_path, self.name)     95      96
   def search(self, query, **params):
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\solvebio\resource\object.py
in upload_file(cls, local_path, remote_path, vault_name)    110
 upload_resp = requests.put(upload_url,    111
           data=open(local_path, 'r'),--> 112
          headers=headers)    113     114         if
upload_resp.status_code != 200:
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\requests\api.py
in put(url, data, **kwargs)    124     """    125 --> 126     return
request('put', url, data=data, **kwargs)    127     128
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\requests\api.py
in request(method, url, **kwargs)     56     # cases, and look like a
memory leak in others.     57     with sessions.Session() as
session:---> 58         return session.request(method=method, url=url,
**kwargs)     59      60
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\requests\sessions.py
in request(self, method, url, params, data, headers, cookies, files,
auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert,
json)    506         }    507         send_kwargs.update(settings)-->
508         resp = self.send(prep, **send_kwargs)    509     510
  return resp
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\requests\sessions.py
in send(self, request, **kwargs)    616     617         # Send the
request--> 618         r = adapter.send(request, **kwargs)    619
620         # Total elapsed time of the request (approximately)
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\requests\adapters.py
in send(self, request, stream, timeout, verify, cert, proxies)    438
                   decode_content=False,    439
retries=self.max_retries,--> 440                     timeout=timeout
 441                 )    442
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\urllib3\connectionpool.py
in urlopen(self, method, url, body, headers, retries, redirect,
assert_same_host, timeout, pool_timeout, release_conn, chunked,
body_pos, **response_kw)    599
           timeout=timeout_obj,    600
                  body=body, headers=headers,--> 601
                                chunked=chunked)    602     603
     # If we're going to release the connection in ``finally:``, then
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\site-packages\urllib3\connectionpool.py
in _make_request(self, conn, method, url, timeout, chunked,
**httplib_request_kw)    355             conn.request_chunked(method,
url, **httplib_request_kw)    356         else:--> 357
conn.request(method, url, **httplib_request_kw)    358     359
# Reset the timeout for the recv() on the socket
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\http\client.py
in request(self, method, url, body, headers, encode_chunked)   1237
             encode_chunked=False):   1238         """Send a complete
request to the server."""-> 1239         self._send_request(method,
url, body, headers, encode_chunked)   1240    1241     def
_send_request(self, method, url, body, headers, encode_chunked):
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\http\client.py
in _send_request(self, method, url, body, headers, encode_chunked)
1283             # default charset of iso-8859-1.   1284
body = _encode(body, 'body')-> 1285         self.endheaders(body,
encode_chunked=encode_chunked)   1286    1287     def
getresponse(self):
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\http\client.py
in endheaders(self, message_body, encode_chunked)   1232         else:
  1233             raise CannotSendHeader()-> 1234
self._send_output(message_body, encode_chunked=encode_chunked)   1235
  1236     def request(self, method, url, body=None, headers={}, *,
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\http\client.py
in _send_output(self, message_body, encode_chunked)   1053
        chunks = (message_body,)   1054 -> 1055             for chunk
in chunks:   1056                 if not chunk:   1057
    if self.debuglevel > 0:
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\http\client.py
in _read_readable(self, readable)   1008             print("encoding
file using iso-8859-1")   1009         while True:-> 1010
datablock = readable.read(blocksize)   1011             if not
datablock:   1012                 break
c:\users\johscot6\appdata\local\continuum\anaconda3\envs\jupyter\lib\encodings\cp1252.py
in decode(self, input, final)     21 class
IncrementalDecoder(codecs.IncrementalDecoder):     22     def
decode(self, input, final=False):---> 23         return
codecs.charmap_decode(input,self.errors,decoding_table)[0]     24
25 class StreamWriter(Codec,codecs.StreamWriter):
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position
61: character maps to <undefined>

**Comment by jsh2134** [comment]
@sajohn2 thanks for the two bugs.

For Issue 1:

How large is the file? S3 has a 5GB file upload limit when not using multi-part upload, which is the default in the python client.....but there are other workarounds for importing this data.

For Issue 2:

Will look into this

P.S. I edited your comment a bit to make the stack trace slightly more readable with code blocks for the stack trace. Unfortunately [github does not support markdown so for email replies,](https://github.com/github/email_reply_parser/issues/25) so I couldn't clean it up totally.

**Comment by davecap** [comment]
Hi Scott,

Were you able to resolve this issue by any chance? Could it have been something with that particular file's contents and/or encoding?
