### ISSUE TITLE
Add shortcut to use a DatasetTemplate for an import

### ISSUE THREAD

**Issue by dandanxu** [solvebio/solvebio-python#245]
right now you have to explicitly grab fields, reader_params, etc, separately from the DatasetTemplate. would be convenient to just set the template

imp = DatasetImport.create(
    dataset_id=dataset.id,
    object_id=object.id,
    target_fields=sb.DatasetTemplate.retrieve(datasettemplate)['fields']
)

**Comment by jsh2134** [comment]
You can now do:

```
template = sb.DatasetTemplate.retrieve(template_id)
imp = DatasetImport.create(
    dataset_id=dataset.id,
    object_id=object.id,
    **template.import_params
)
```
