### ISSUE TITLE
Request - Shortcuts for creating folders with descriptions (or bug where create_folder doesn't allow slashes?)

### ISSUE THREAD

**Issue by dandanxu** [solvebio/solvebio-python#251]
I'm trying to update new versions of public datasets and would like to make it easier/more automated in the future. Right now I add descriptions for each version in the UI but ideally I'd be able to just add automated descriptions to the folders as they're created. This is fairly easy for new datasets, but pretty awkward for new folders.

To create a specific folder with a description, I have to first specify the vault, then make a new folder, then make a new folder within that folder with the description, then concatenate all the paths together to make the dataset path and then create the dataset.
I guess alternatively I can create a dataset from a path, then find the folder that's auto-created and then give that a description (which isn't so bad).

my initial code was
```
    vault_path = 'solvebio:blahblah'
    vault = solvebio.Vault.get_by_full_path(vault_path)

    folder_path = 'SomeDataset/SomeSchemaVersion-' + data_dump_version
    folder_description = data_dump_version + ' version downloaded from some url'
    vault.create_folder(folder_path, description=folder_description)

    dataset_full_path = ''.join(
        vault_path,
        ':/',
        folder_path,
        '/',
        dataset_type.title()
    )

    # create a large SolveBio Dataset
    dataset = solvebio.Dataset.get_or_create_by_full_path(
        dataset_full_path,
        fields=tpl_json['fields'],
        capacity='large',
        description=metadata['dataset_type']
    )
```
but this creates the error
`SolveError:  {u'field_errors': [{u'field': u'filename', u'message': [u'Filename cannot contain slashes']}]}`

because my folder path has slashes in it.

anyways, if someone has a shorter way of just creating a folder with a description and then putting a dataset into it, that would be great

**Comment by jsh2134** [comment]
Starting in v2.10 -> You could now use Object.get_or_create_by_full_path() to do this all in one request. The one thing you would still have to do is assign a description to the folder. New (untested) code

```
    vault_path = 'solvebio:blahblah'
    folder_path = 'SomeDataset/SomeSchemaVersion-' + data_dump_version
    dataset_full_path = ''.join(
        vault_path,
        ':/',
        folder_path,
        '/',
        dataset_type.title()
    )
    # create a large SolveBio Dataset
    dataset = solvebio.Object.get_or_create_by_full_path(
        dataset_full_path,
        fields=tpl_json['fields'],
        capacity='large',
        description=metadata['dataset_type']
    )

    folder = dataset.parent
    folder.description = data_dump_version + ' version downloaded from some url'
    folder.save()

```
