### ISSUE TITLE
Shortcut to create a new file object in a SolveBio vault from an export

### ISSUE THREAD

**Issue by dandanxu** [solvebio/solvebio-python#274]
This will make it easier to give file-based deliverables for projects. Right now I'm downloading the exports to my local computer and then re-uploading manually into a vault. It'd be nice if an export could be created as a file in the SolveBio vault instead.

**Comment by jsh2134** [comment]
added in #310 

```
dataset.query().export(target_full_path='my_vault:/path/to/my/json_files')
```
