### ISSUE TITLE
Modifying object attributes that are dictionaries may not save updates 

### ISSUE THREAD

**Issue by jsh2134** [solvebio/solvebio-python#276]
If you modify a dictionary on an APIResource and then save() the resource, the updates are not sent. This is because  [__setitem__ is not getting called on the resource](https://github.com/solvebio/solvebio-python/blob/35044c3303e84a8ee7e08a8a8ee6184080b0e668/solvebio/resource/solveobject.py#L63) in this case and not updating the `_unsaved_values` set.

Example
```
# Failure case
print obj.metadata
{}
obj.metadata['foo'] = 'bar'
obj.save()
# nada
print obj.metadata
{}

# Workaround
obj.metadata = {'foo': 'bar'}
obj.save()
print obj.metadata
{'foo': 'bar'}
```

**Comment by davecap** [comment]
That makes sense, maybe when we construct the nested solveobject ([here](https://github.com/solvebio/solvebio-python/blob/master/solvebio/resource/solveobject.py#L80) and [here](https://github.com/solvebio/solvebio-python/blob/master/solvebio/resource/solveobject.py#L25)) we can set the parent object as a hidden attribute. When setitem is called on the nested SolveObject we can add the attribute to `_unsaved_values` on the parent. We may only want to do this on SolveObjects (i.e. not on other types of nested objects).
