### ISSUE TITLE
Give Object instances that represent "datasets" the ability to be queried

### ISSUE THREAD

**Issue by davecap** [solvebio/solvebio-python#287]
It can be confusing that Objects are also Datasets but they don't have the same helper functions (like "query()". If an Object is a type "dataset", it should be possible to at least query it. How can we blend the Dataset class into the Object class?

One way is to have different sub-classes for each Object type, like `DatasetObject`, `FileObject`, `FolderObject`. Or we can deprecate the `Dataset` class itself and replace it with a subclass of Object (called `Dataset`), and add `File` and `Folder` subclasses.

**Comment by jsh2134** [comment]
in #315 I added a pass-through for query() so now you can do `Object.retrieve(dataset_id).query(**)`

however there are still 10+ other methods that are on the Dataset object that may be wanted (dataset.beacon(), dataset.activity() etc...)

**Comment by davecap** [comment]
What about adding a `__getattr__` and returning the result of getattr(Dataset, "attr") if the object type is dataset? We can limit the list of valid attrs to "beacon, activity, etc.." if we want.
