### ISSUE TITLE
[DashAuth] Specify cookie `max_age` to prevent immediate expiry

### ISSUE THREAD

**Issue by davidhpark** [solvebio/solvebio-python#296]
Currently, the `max_age` parameter is not set, resulting in the immediate expiry of the cookies. This forces users to always log in whenever they close their browsers. One solution would be to set the `max_age` to a week in `SolveBioAuth`.

Related: solvebio/www.solvebio.com#1580

**Comment by davecap** [comment]
Ideally we can make this a configurable parameter somehow, possibly when creating the Dash app object. One way to do this is to add the ability to pass a custom SolveAuth object through __init__.
