### ISSUE TITLE
Metadata as class<str> after saving empty metadata

### ISSUE THREAD

**Issue by PolinaBevad** [solvebio/solvebio-python#324]
I’m not sure if it is a bug or not: if I save empty metadata to an object (and metadata’s type is dict), then next time when I try to get this metadata, it’s type will be str. Code to reproduce:

    folder = Object.retrieve(some_id_here) 
    metadata = {}
    print(type(metadata)) # <class 'dict'>
    folder.metadata = metadata
    folder.save() 
    metadata = folder.metadata
    print(type(metadata))  # <class 'str'>

Found this when was copying metadata from parent folder and it was empty.

**Comment by jsh2134** [comment]
Yes this is an API bug. We use a JSON Field for the metadata and technically `""` is valid JSON. It should be fixed to return {}

**Comment by davecap** [comment]
Confirming that this has been fixed in the API. The API now returns `{}` which is loaded by the client as type `SolveObject`.
