### ISSUE TITLE
Error on updating fields in DatasetTemplate

### ISSUE THREAD

**Issue by PolinaBevad** [solvebio/solvebio-python#344]
Hi all! 
I was trying to do these (Solvebio 2.9.0):
`template = DatasetTemplate.retrieve(my_template_id)`
` template['fields'] = fields`
 `template.save()`

But have the default error on saving: `solvebio.errors.SolveError: Unexpected error communicating with SolveBio. If this problem persists, let us know at support@solvebio.com.`

It is not critical, but sometimes you want to rewrite old template fields instead of creating new one. 

Thank you!

**Comment by jsh2134** [comment]
This is a backend issue and has been resolved.
