### ISSUE TITLE
Possible improvement: update description/expression if field was updated via migration

### ISSUE THREAD

**Issue by PolinaBevad** [solvebio/solvebio-python#360]
Hi all,

I have a use case, not critical, but perhaps some improvement can be made here.

We have some datasets where field was filled in one way at one moment. After a while we want to update this field, but its logic and expression will be changed. At the moment if we use `target_fields` in dataset.migrate(), the values in field will be updated, but `expression`, `description`, `depends_on`, etc - will not. 

It can be a little confusing when you look at updated field in UI, as logic of its calculation was changed, but we can't say about this from the field description. I can update such fields manually (via DatasetField: `field.description = "some desc"`  and `field.save()`), but it needs few additional steps. 

It would be great if you can consider a possibility to update at least `description` and `expression` after migration, if they were changed.
Thank you!

**Comment by davecap** [comment]
Yes I believe we can do this. Just to summarize, you would like the description and expression to be updated to whatever the latest values were applied in the most recent migration.

**Comment by davecap** [comment]
This has been fixed on the backend.
