### ISSUE TITLE
Bug in restore dataset functionality

### ISSUE THREAD

**Issue by PolinaBevad** [solvebio/solvebio-python#407]
Hi David and Tatjana,

I found the small bug in restore dataset functionality [here](https://github.com/solvebio/solvebio-python/blob/a9c11438d3ccc58f75b1c18b25e9374287b05ec4/solvebio/resource/object.py#L604)

If we do not pass any desired storage class to function, it will be overwritten by None here:

        if not storage_class:
            self.storage_class = "Standard"
        ...
        self.storage_class = storage_class

**Comment by davecap** [comment]
Nice catch! Will fix in the next release.
