### ISSUE TITLE
Easy way to pull out latest available datasets for retrieval in the API

### ISSUE THREAD

**Issue by dandanxu** [solvebio/solvebio-python#55]
Right now I'm still going back to the website (www.solvebio.com/library) every time I want a new dataset to pull out the exact dataset name for the one I'm interested in.
I know that solvebio.Depository.all() exists, but it's too bulky to quickly scan by eye.
Would really like something like solvebio.Depository.latest()
that brings me just a concise non-detailed list like:
ClinVar/2.0.0-1/Variants
ClinVar/2.0.0-1/Submissions
ClinVar/2.0.0-1/Phenotypes
HGNC/1.0.0-1/HGNC
and the dataset IDs or something.

related: Would it be possible to make an auto-complete or something for solvebio.Dataset.retrieve so that when I start typing solvebio.Dataset.retrieve('C -- and tabs, it brings up ClinVar? or too complicated?

**Comment by davecap** [comment]
`Dataset.all(latest=True)`
